my_list=list(map(int,input().split("@")))
choice=int(input())
print(*my_list)
if(choice==1):
    my_list.append(99)
    print(my_list)
elif(choice==2):
    my_list.pop(0)
    print(my_list)
elif(choice==3):
    my_list.sort()
    print(my_list)
elif(choice==4):
    print("hello")